jobs:
- name: verify-compliance
  public: true
  plan:
  - get: compliance-repository
  - get: scripts
  - task: run-compliance-masonry
    file: scripts/task-run-compliance-masonry.yml
  - put: deploy-documentation
    params:
      manifest: compliance-repository/manifest.yaml
      path: compliance-repository

resources:
- name: compliance-repository
  type: git
  source:
    uri: https://github.com/18F/cg-compliance.git
- name: scripts
  type: git
  source:
    uri: https://github.com/geramirez/Concourse-Compliance-Masonry.git
- name: deploy-documentation
  type: cf
  source:
    api: {{API}}
    username: {{USERNAME}}
    password: {{PASSWORD}}
    organization: {{ORG}}
    space: {{SPACE}}
